piro18_Ajax_Pirostagram/server/apps/insta/urls.py
from django.urls import path
from . import views

app_name = "insta"

urlpatterns = [
  path("", views.main, name="main"),
  path('insta/create/', views.insta_create, name='create'),
  path("insta/likes/<int:pk>", views.likes, name="likes"),
  path("insta/comment/<int:pk>", views.comment, name="comment"),
  path("insta/comment/<int:pk>/create", views.comment_create, name="comment_create"),
  path("insta/comment/<int:pk>/delete", views.comment_delete, name="comment_delete"),
  path("signup/", views.signup, name="signup"),
  path("login/", views.login, name="login"),
  path("logout/", views.logout, name="logout"),
]

piro18_Ajax_Pirostagram/server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("",include("server.apps.insta.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piro18_Ajax_Pirostagram/server/apps/insta/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    login_id = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='write_posts')
    content = models.TextField()
    image = models.ImageField(blank=True, null=True)
    like_users = models.ManyToManyField(User, null=True, related_name='like_posts')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='write_comments')
    related_post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='related_post')
    content = models.TextField()
    like_users = models.ManyToManyField(User, null=True, related_name='like_comments')
    created_at = models.DateTimeField(auto_now_add=True)

piro18_Ajax_Pirostagram/server/apps/insta/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

piro18_Ajax_Pirostagram/server/apps/insta/views.py
from django.shortcuts import render, redirect
from server.apps.insta.forms import SignupForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import auth
from server.apps.insta.models import User, Post, Comment
import json
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth.login(request, user)      
            return render(request, "insta/main.html")
        else:
            return redirect('insta:signup')
    else:
        form = SignupForm()
        context = {
            'form': form,
        }
        return render(request, template_name='insta/signup.html', context=context)

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('insta:main')
        else:
            context = {
                'form': form,
                'user': user
            }
            return render(request, template_name='insta/login.html', context=context)
    else:
        form = AuthenticationForm()
        context = {
            'form': form,
        }
        return render(request, template_name='insta/login.html', context=context)


def logout(request):
    auth.logout(request)
    return redirect('insta:main')

def main(request):
    user = request.user
    if user.is_authenticated:
        user_name = User.objects.get(username=user)
        posts = Post.objects.order_by('-created_at')
        comments = Comment.objects.all()
        context = {'user': user, 'posts':posts, 'comments':comments}
        liked_users = posts.filter(like_users=user)
        if liked_users.count():
            context['liked_users'] = liked_users
    else:
        context = {'user': user }
    
    return render(request, "insta/main.html", context=context)

def insta_create(request):
    user = request.user
    if request.method == "POST":
        Post.objects.create(
            user = User.objects.get(username=user),
            content = request.POST['content'],
            image = request.FILES.get("image"),
        )
        return redirect("insta:main")
    return render(request, "insta/insta_create.html")

@csrf_exempt
def likes(request, pk):
    user = request.user
    if user.is_authenticated:
        req = json.loads(request.body)
        post_id = req['id']
        btn_type = req['type']
        post = Post.objects.get(id=post_id)
        if btn_type == 'like':
            post.like_users.add(user)
        else:
            post.like_users.remove(user)
            
        post.save()
        return JsonResponse({'id' : post_id, 'type': btn_type})
 
@csrf_exempt
def comment(request, pk):
    user = request.user
    post = Post.objects.get(id=pk)
    comments = Comment.objects.order_by('created_at')
    context = {'user':user, 'post':post, 'comments':comments,}
    return render(request, "insta/comment.html", context=context)

@csrf_exempt
def comment_create(request, pk):
    user = request.user
    if user.is_authenticated:
        req = json.loads(request.body)
        post_id = req['post_id']
        user = req['user']
        comment = req['comment']
        user_id = User.objects.get(username=user).pk
        Comment.objects.create(
            user = User.objects.get(id=user_id),
            related_post = Post.objects.get(id=post_id),
            content = comment
        )
        comment_id = Comment.objects.last().pk
        return JsonResponse({'post_id' : post_id, 'user': user, 'comment':comment, 'comment_id':comment_id})
    
@csrf_exempt
def comment_delete(request, pk):
    user = request.user
    if user.is_authenticated:
        req = json.loads(request.body)
        post_id = req['post_id']
        comment_id = req['comment_id']
        target_comment = Comment.objects.get(id=comment_id)
        target_comment.delete()
        return JsonResponse({'post_id' : post_id, 'comment_id':comment_id})

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/comment.html
{% extends 'insta/navbar.html' %}
{% load static %}

{% block content %}
{% if user.is_authenticated %}
<div class="mx-5">
    <h4 class="mt-5 pt-5 ">댓글</h4>
    <div id="container"> 
    {% for comment in comments %}
    {% if comment.related_post.id == post.id  %}
        <div class="d-flex justify-content-between align-items-center" id="{{comment.id}}">
            <div>{{comment.user}} :  {{comment.content}}</div>
            {% if comment.user.id == user.id  %}
            <div class="my-1 btn btn-sm bg-secondary text-white" onclick="onClickDelete({{ post.id }}, {{ comment.id }})">삭제</div>
            {% endif %}
        </div>
    {% endif %}
    {% endfor %}
    </div>
    <div>
        <input type="text" id="comment_text" placeholder="댓글을 작성해보세요">
        <button class="btn bg-secondary text-white" onclick="onClickLike({{ post.id }}, '{{user}}', comment_text.value)">게시</button>
    </div>
</div>
{% endif %}
<script>
    const strip = (string) => {
        return string.replace(/^\s+|\s+$/g, "");
        };
    const requestLike = new XMLHttpRequest();
    const onClickLike = (post_id, user, comment) => {
        const url = "/insta/comment/" + post_id + "/create";
        requestLike.open("POST", url, true)
        requestLike.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({post_id: post_id, user: user, comment: comment}));
    };

    requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
            if (requestLike.status < 400) {
                const { post_id, user, comment, comment_id } = JSON.parse(requestLike.response);
                const target = document.querySelector(`#container`);
                const newComment = document.createElement('div');
                newComment.id= comment_id;
                newComment.className='d-flex justify-content-between align-items-center';
                newComment.innerHTML = `<div>${user}  :  ${comment}</div>
                <div class="my-1 btn btn-sm bg-secondary text-white" onclick="onClickDelete(${ post_id }, ${ comment_id })">삭제</div>`;
                target.appendChild(newComment);
            }
        }
    };


    const requestDelete = new XMLHttpRequest();
    const onClickDelete = (post_id, comment_id) => {
        const url = "/insta/comment/" + post_id + "/delete";
        requestDelete.open("POST", url, true)
        requestDelete.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestDelete.send(JSON.stringify({post_id: post_id, comment_id: comment_id}));
    };

    requestDelete.onreadystatechange = () => {
        if (requestDelete.readyState === XMLHttpRequest.DONE) {
            if (requestDelete.status < 400) {
                const { post_id, comment_id } = JSON.parse(requestDelete.response);
                const targetContainer = document.querySelector(`#container`);
                const target = document.getElementById(`${comment_id}`);
                targetContainer.removeChild(target);
            }
        }
    };
</script>
{% endblock %}

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/comment_create.html
{% extends 'insta/navbar.html' %}
{% load static %}

{% block content %}
<div class="py-5 my-4 d-flex flex-column  align-items-center">
    <form action="{% url 'insta:comment_create' post.id %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <h4>댓글 작성</h4>
        <textarea name="content" id="" cols="30" rows="10"></textarea>
        <br />
        <input type="submit", value="저장하기", class="btn bg-secondary text-white">
    </form>
</div>
{% endblock %}

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/insta_create.html
{% extends 'insta/navbar.html' %}
{% block content %}
<div class="py-5 my-4 d-flex flex-column  align-items-center">
    <form action="{% url 'insta:create' %}" method='post' enctype="multipart/form-data">
        {% csrf_token %}
        <p>게시글 작성</p>
        <input type="file" name="image" />
        <br />
        <textarea name="content" id="" cols="30" rows="10"></textarea>
        <br />
        <input type="submit", value="저장하기", class="btn bg-secondary text-white">
    </form>
</div>
{% endblock %}

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/login.html
{% extends 'insta/navbar.html' %}
{% block content %}
    <div class="py-5 my-4 d-flex justify-content-center align-items-center p-5" id="login-box">
        <div class="" id="login-con">
            <form method="POST" action="" class="py-3">
                {% csrf_token %}
                {{ form }}
                <button class="btn bg-secondary text-white mx-3">Login</button>
            </form>
            <span>회원가입이 되어있지 않으신가요?</span>
            <a href="{% url 'insta:signup' %}" class="btn bg-secondary text-white mx-3">회원가입</a>
        </div>
    </div>
{% endblock %}

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/main.html
{% extends 'insta/navbar.html' %}
{% load static %}
{% block content %}
  <div class="py-5 my-4 d-flex flex-column align-items-start">
    {% if user.is_authenticated %}
      {% for post in posts %}
        {% if post.image %}
          <div style="width: 100vw; height: 100vw;"><img style="width: 100%; height:100%" src="{{ post.image.url }}" alt=""></div>
        {% endif %}
        <div class="d-flex flex-row justify-content-start">
          <div class="d-flex flex-row mx-2 my-1 post-id-{{ post.id }}">
            {% if post in liked_users %}
              <div class="post__dislike" onclick="onClickLike({{ post.id }}, 'dislike')"><i class="fa-solid fa-heart fa-2x"></i></div>
            {% else %}
              <div class="post__like" onclick="onClickLike({{ post.id }}, 'like')"><i class="fa-regular fa-heart fa-2x"></i></div>
            {% endif %}
          </div>
          <div><a href="{% url "insta:comment" post.pk %}"><i class="mx-2 my-1 fa-regular fa-comment fa-2x"></i></a></div>
        </div>
        <div class="d-flex flex-column mx-2">
          <div>{{post.user}} : {{ post.content }}</div>
          <hr/>
          {% for comment in comments %}
            {% if comment.related_post.id == post.id %}
              <div>{{comment.user}}  :  {{comment.content}}</div>
            {% endif %}
          {% endfor %}
          
        </div>
        <hr/>
      {% endfor %}
    {% endif %}
  </div>
  <script>
    const strip = (string) => {
        return string.replace(/^\s+|\s+$/g, "");
      };
    const requestLike = new XMLHttpRequest();
    const onClickLike = (id, type) => {
        const url = "/insta/likes/" + id;
        requestLike.open("POST", url, true)
        requestLike.setRequestHeader(
            "Content-Type",
            "application/x-www-form-urlencoded"
        );
        requestLike.send(JSON.stringify({id: id, type: type}));
    };

    requestLike.onreadystatechange = () => {
        if (requestLike.readyState === XMLHttpRequest.DONE) {
            if (requestLike.status < 400) {
                const { id, type } = JSON.parse(requestLike.response);
                const element = document.querySelector(`.post-id-${id}`);
                const originHTML = strip(element.innerHTML);
                console.log(originHTML)
                if (originHTML.includes('fa-solid')) {
                  element.innerHTML = `<div class="post__like" onclick="onClickLike(${id}, 'like')"><i class="fa-regular fa-heart fa-2x"></i></div>`;
                  console.log(element)
                } else {
                  element.innerHTML = `<div class="post__dislike" onclick="onClickLike(${id}, 'dislike')"><i class="fa-solid fa-heart fa-2x"></i></div>`;
                  console.log(element)
                };
            }
        }
    };
  </script>
{% endblock %}

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>insta cloning</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <script src="https://kit.fontawesome.com/f95b2ab384.js" crossorigin="anonymous"></script>
</head>
<body>
  <header class="py-2 d-flex justify-content-between align-items-center px-3 bg-black">
    <a href="{% url 'insta:main' %}"><i class="fa-solid fa-chevron-left"></i></a>
    {% if user.is_authenticated %}
    <div class="d-flex flex-column justify-content-center align-items-center">
      <div class="nav_id">{{ user }}</div>
      <div>게시물</div>
    </div>
      <div class="d-flex">
        <a href="{% url 'insta:logout' %}" class="">로그아웃</a>
      </div>
    {% else %}
    <div class="d-flex flex-column justify-content-center align-items-center">
      <div class="nav_id">로그인해주세요</div>
      <div>게시물</div>
    </div>
      <a href="{% url 'insta:login' %}" class="">로그인</a>
    {% endif %}
  </header>
  {% block content %}
  {% endblock %}
  <footer>
    <div class="footer__container">
      <a class="footer__item"><i class="fas fa-home"></i></a>
      <a class="footer__item"><i class="fas fa-search"></i></a>
      <a class="footer__item" href="{% url 'insta:create' %}"><i class="far fa-plus-square"></i></a>
      <a class="footer__item"><i class="far fa-heart"></i></a>
      <a class="footer__image"><img src="http://placekitten.com/300/300" alt="" /></a>
    </div>
  </footer>
  
</body>
</html>

piro18_Ajax_Pirostagram/server/apps/insta/templates/insta/signup.html
{% extends 'insta/navbar.html' %}
{% block content %}
<div class="py-5 my-4 d-flex justify-content-center align-items-center p-5" id="login-box">
    <div class="bg-light" id="login-con">
        <form method="POST" action="{% url 'insta:signup' %}">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="SignUp">
        </form>
    </div>
</div>
{% endblock %}