SWIDEA_SITE/server/apps/ideas/urls.py
from django.urls import path
from . import views

app_name = "ideas"

urlpatterns= [
    path("", views.ideas_list, name="list"),
    path("ideas/create", views.ideas_create, name="create"),
    path("ideas/<int:pk>", views.ideas_read, name="read"),
    path("ideas/<int:pk>/update", views.ideas_update, name="update"),
    path("ideas/<int:pk>/delete", views.ideas_delete, name="delete"),
    
    path("devtool", views.devtools_list, name="devtool_list"),
    path("devtool/create", views.devtools_create, name="devtool_create"),
    path("devtool/<int:pk>", views.devtools_read, name="devtool_read"),
    path("devtool/<int:pk>/update", views.devtools_update, name="devtool_update"),
    path("devtool/<int:pk>/delete", views.devtools_delete, name="devtool_delete"),
]

SWIDEA_SITE/server/apps/ideas/models.py
from django.db import models

# Create your models here.
class Devtool(models.Model):
    name = models.CharField(max_length=64, blank=True)
    kind = models.CharField(max_length=64, blank=True)
    content = models.CharField(max_length=64, blank=True)
        
# class Like(models.Model):
#     liked = models.BooleanField(default=False)
    
class Idea(models.Model):
    title = models.CharField(max_length=64)
    image = models.ImageField(blank=True, upload_to='ideas/%Y%m%d', null=True)
    content = models.TextField()
    interest = models.IntegerField()
    devtool = models.ForeignKey(Devtool, on_delete=models.CASCADE, related_name="idea_devtool")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    star = models.BooleanField(default=False)
    
    

SWIDEA_SITE/server/apps/ideas/views.py
from django.shortcuts import render, redirect
from server.apps.ideas.models import Idea, Devtool
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def ideas_list(request, *args, **kwargs):
    search_mode = request.GET.get('search_mode')
    context = {
        'option_list' : ['기본', '찜하기순', '이름순', '등록순', '최신순']
    }
    
    if request.method == 'POST':
        like_id = request.POST.get('like')
        like_idea = Idea.objects.get(id=like_id)
        trueorfalse = request.POST.get('trueorfalse')
        print(like_idea.star, trueorfalse)
        if trueorfalse == 'True':
            like_idea.star = True
            like_idea.save()
            return redirect("/")
        else:
            like_idea.star = False
            like_idea.save()
            return redirect("/")
            
    if search_mode:
        if search_mode == '기본':
            ideas = Idea.objects.all()
            default_option = '기본'
        elif search_mode == '찜하기순':
            ideas = Idea.objects.filter(star=True)
            default_option = '찜하기순'
        elif search_mode == '이름순':
            ideas = Idea.objects.order_by('title')
            default_option = '이름순'
        elif search_mode == '등록순':
            ideas = Idea.objects.order_by('-created_at')
            default_option = '등록순'
        elif search_mode == '최신순':
            ideas = Idea.objects.order_by('-updated_at')
            default_option = '최신순'
    else:
        ideas = Idea.objects.all()
        default_option = '기본'
        
    context['ideas'] = ideas
    context['default_option'] = default_option
    return render(request, "ideas/ideas_list.html", context=context)

def ideas_create(request, *args, **kwargs):
    if request.method == "POST":
        devtool_id = request.POST["devtool"]
        Idea.objects.create(
            title=request.POST["title"],
            image=request.FILES.get("image"),
            content=request.POST["content"],
            interest=request.POST["interest"],
            devtool=Devtool.objects.get(id=devtool_id),
        )
        new = Idea.objects.last()
        return redirect("/ideas/{}".format(new.id))
    
    devtools = Devtool.objects.all()
    
    context = {
        'devtools' : devtools,
    }
    
    return render(request, "ideas/ideas_create.html",context=context)

def ideas_read(request, pk, *args, **kwargs):
    idea = Idea.objects.get(id=pk)
    
    context = {
        'idea' : idea,
    }
    
    return render(request, "ideas/ideas_read.html", context=context)

def ideas_update(request, pk, *args, **kwargs):
    idea = Idea.objects.get(id=pk)
    devtools = Devtool.objects.all()
    
    context = {
        'idea' : idea,
        'devtools' : devtools,
    }
    
    if request.method == "POST":
        devtool_id = request.POST["devtool"]
        
        idea.title=request.POST["title"]
        if request.FILES.get("image"):
            idea.image=request.FILES["image"]
        if request.POST.get("check"):
            idea.image = None
        idea.content=request.POST["content"]
        idea.interest=request.POST["interest"]
        if devtool_id:
            idea.devtool=Devtool.objects.get(id=devtool_id)
        idea.save()
        return redirect("/ideas/{}".format(idea.id))
    
    return render(request, "ideas/ideas_update.html", context=context)

def ideas_delete(request, pk, *args, **kwargs):
    if request.method == "POST":
        idea = Idea.objects.get(id=pk)
        idea.delete()
    return redirect("/")

##############################################################################################################

def devtools_list(request, *args, **kwargs):
    devtools = Devtool.objects.all()
    
    context = {
        "devtools" : devtools,
    }
    
    return render(request, "devtools/devtools_list.html", context=context)
    
def devtools_create(request, *args, **kwargs):
    if request.method == "POST":
        Devtool.objects.create(
            name=request.POST["name"],
            kind=request.POST["kind"],
            content=request.POST["content"],
        )
        new_devtool = Devtool.objects.last()
        return redirect("/devtool/{}".format(new_devtool.id))
    return render(request, "devtools/devtools_create.html")
    
def devtools_read(request, pk, *args, **kwargs):
    devtool = Devtool.objects.get(id=pk)
    all_ideas = devtool.idea_devtool.all()
    context = {
        'devtool' : devtool,
        'all_ideas' : all_ideas
    }
    
    return render(request, "devtools/devtools_read.html", context=context)

def devtools_update(request, pk, *args, **kwargs):
    devtool = Devtool.objects.get(id=pk)
    
    context = {
        'devtool' : devtool,
    }
    
    if request.method == "POST":
        devtool.name = request.POST["name"]
        devtool.kind = request.POST["kind"]
        devtool.content = request.POST["content"]
        devtool.save()
        return redirect("/devtool/{}".format(devtool.id))
        

    return render(request, "devtools/devtools_update.html", context=context)

def devtools_delete(request, pk, *args, **kwargs):
    if request.method == "POST":
        devtool = Devtool.objects.get(id=pk)
        devtool.delete()
    return redirect("/devtool")

SWIDEA_SITE/server/apps/ideas/templates/devtools/devtools_create.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DEVTOOL REGISTER</title>
    <link rel="stylesheet" href="{% static 'css/devtools_create.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <h2 class="main_topic">Devtool Register</h2>
        <h3 class="main_info">개발툴 등록 페이지! 생각날 때마다 업데이트 합시다</h3>
        <div class="main_posts">
            <hr />
            <form action="{% url 'ideas:devtool_create' %}" method="post">
                {% csrf_token %}
                <p>개발툴 명 :</p>
                <input name="name" />
                <br />
                <p>개발툴 종류 :</p>
                <input name="kind" />
                <br />
                <p>개발툴 설명 :</p>
                <textarea name="content"></textarea>
                <br />
                <div>
                    <input type="submit", value="저장하기" />
                </div>
            </form>
            <hr />
        </div>
    </div>
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/devtools/devtools_list.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DEVTOOL LIST</title>
    <link rel="stylesheet" href="{% static 'css/devtools_list.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <h2 class="main_topic">Devtool List</h2>
        <h3 class="main_info">내가 사용할 수 있는 개발툴 목록! 계속 늘려나갑시다</h3>
        <div class="main_posts">
            <hr />
            {% for devtool in devtools %}
            <article class="main_post">
                <span><a href="{% url 'ideas:devtool_read' devtool.pk %}">{{ devtool.name }}</a></span>
                <span>{{ devtool.kind }}</span>
                <span>{{ devtool.content }}</span>
            </article>
            <hr />
            {% endfor %}
        </div>
    </div>
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/devtools/devtools_read.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DEVTOOL DETAIL</title>
    <link rel="stylesheet" href="{% static 'css/devtools_read.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <div class="main_topic">Devtool Detail</div>
        <div class="main_info">개발툴 세부페이지! 다음에 봐도 기억나게 상세히 수정해두자</div>
        <div class="main_post">
            <h1>{{ devtool.name }}</h1>
            <p>{{ devtool.kind }}</p>
            <p>{{ devtool.content }}</p>
            <hr />
            <p>>만들 수 있는 SW 목록</p>
            {% for each_idea in all_ideas %}
                <a href="{% url 'ideas:read' each_idea.id %}">{{ each_idea.title }}</a>
            {% endfor %}
        </div>
        <div>
            <a href="{% url 'ideas:devtool_list' %}">목록으로</a>
        </div>
        <div>
            <a href="{% url 'ideas:devtool_update' devtool.pk %}">수정하기</a>
        </div>
        <form action="{% url 'ideas:devtool_delete' devtool.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" , value="삭제하기" />
        </form>
    </div>
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/devtools/devtools_update.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DEVTOOL MODIFY</title>
    <link rel="stylesheet" href="{% static 'css/devtools_create.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <h2 class="main_topic">Devtool Modify</h2>
        <h3 class="main_info">개발툴 수정 페이지! 수정 사항이 생기면 바로바로 업데이트 합시다</h3>
        <div class="main_posts">
            <hr />
            <form action="{% url 'ideas:devtool_update' devtool.pk %}" method="post">
                {% csrf_token %}
                <p>개발툴 명 :</p>
                <input name="name" value="{{ devtool.name }}" />
                <br />
                <p>개발툴 종류 :</p>
                <input name="kind" value="{{ devtool.kind }}" />
                <br />
                <p>개발툴 설명 :</p>
                <textarea name="content">{{ devtool.content }}</textarea>
                <br />
                <div>
                    <input type="submit", value="저장하기" />
                </div>
            </form>
            <hr />
        </div>
    </div>
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/ideas/ideas_create.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IDEA REGISTER</title>
    <link rel="stylesheet" href="{% static 'css/ideas_create.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <h2 class="main_topic">Idea Register</h2>
        <h3 class="main_info">아이디어 등록 페이지! 생각날 때마다 업데이트 합시다</h3>
        <div class="main_posts">
            <hr />
            <form action="{% url 'ideas:create' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>아이디어 명 :</p>
                <input name="title" />
                <br />
                <p>이미지 등록 :</p>
                <input type="file" name="image" />
                <br />
                <p>아이디어 설명 :</p>
                <textarea name="content"></textarea>
                <br />
                <p>아이디어 관심도 :</p>
                <input name="interest" />
                <br />
                <p>예상 개발툴 :</p>
                <select name="devtool" id="devtool">
                    <option value="" selected>-------</option>
                    {% for devtool in devtools %}
                    <option value="{{ devtool.id }}" name="devtool">{{ devtool.name }}</option>
                    {% endfor %}
                </select>
                <br />
                <div>
                    <input type="submit", value="저장하기" />
                </div>
            </form>
            <hr />
        </div>
    </div>
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/ideas/ideas_list.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IDEA LIST</title>
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/ideas_list.css' %}?after ">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <div class="main_topic">Idea List</div>
        <div class="main_info">나의 아이디어를 잊지말고 기록해두자</div>
        <form action="{% url 'ideas:list' %}" method="get" id="search_mode">
            <select name="search_mode" id="search_mode">
                <option value="">{{ default_option }}</option>
                {% for option in option_list %}
                {% if option != default_option %}
                    <option value={{ option }}>{{ option }}</option>
                {% endif %}
                {% endfor %}
            </select>
        </form>
        <div class="main_posts">
            {% for idea in ideas %}
            <article>
                {% if idea.image %}
                <p class="checkbox_container">
                    <img src="{{ idea.image.url }}" alt="">
                </p>
                {% endif %}

                {% if not idea.star %}
                    <form action="{% url 'ideas:list' %}" method="post" class="like">
                        {% csrf_token %}
                        <input type="submit" class="like" value="찜하기">
                        <span>현재 상태 : 찜X</span>
                        <input type="hidden" name="trueorfalse" value="True">
                        <input type="hidden" name="like" value="{{idea.id}}">
                    </form>
                {% else %}
                    <form action="{% url 'ideas:list' %}" method="post" class="like">
                        {% csrf_token %}
                        <input type="submit" class="like" value="찜취소">
                        <span>현재 상태 : 찜</span>
                        <input type="hidden" name="trueorfalse" value="False">
                        <input type="hidden" name="like" value="{{idea.id}}">
                    </form>
                {% endif %}

                <h3><a href="{% url 'ideas:read' idea.pk %}">{{ idea.title }}</a></h3>
                <small>예상 개발 툴 : {{ idea.devtool.name }}</small>
                <br />
                <small>아이디어 관심도 : <button name="plus">+</button>  <span class="interest">{{ idea.interest }}</span>  <button name="minus">-</button></small>
                <br />
            </article>
            {% endfor %}
        </div>
    </div>
    <script type="text/javascript">
        $(document).ready(function(){
            $("select[name=search_mode]").change(function () {
            $("#search_mode").submit();
            });
        });
    </script>
    <!-- <script type="text/javascript">
        $('button[name=plus]').on('click', function(e) {
            data = $('.interest').val();

            $.ajax({
                type:'POST',
                url:'http://127.0.0.1:8000/',
                data:JSON.stringify(data),
                success:function(json){
                    console.log("data pass success",json);
                },
                error : function(xhr,errmsg,err) {
                console.log(xhr.status + ": " + xhr.responseText); 
                }
           });
          });
    </script> -->
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/ideas/ideas_read.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IDEA DETAIL</title>
    <link rel="stylesheet" href="{% static 'css/ideas_read.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <div class="main_topic">Idea Detail</div>
        <div class="main_info">아이디어 기록 세부페이지! 다음에 봐도 기억나게 상세히 수정해두자</div>
        <div class="main_post">
            {% if idea.image %}
                <p><img src="{{ idea.image.url }}" alt=""></p>
            {% endif %}
            <h1>{{ idea.title }}</h1>
            <p>아이디어 관심도 : {{ idea.interest }}</p>
            <p>예상 개발 툴 : <a href="{% url 'ideas:devtool_read' idea.devtool.id %}">{{ idea.devtool.name }}</a></p>
            <p>아이디어 설명 : {{ idea.content }}</p>
            {% if idea.star %}
                <p>찜 여부 : O</p>
            {% else %}
                <p>찜 여부 : X</p>
            {% endif %}
        </div>
        <div>
            <a href="{% url 'ideas:list' %}">목록으로</a>
        </div>
        <div>
            <a href="{% url 'ideas:update' idea.pk %}">수정하기</a>
        </div>
        <form action="{% url 'ideas:delete' idea.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" , value="삭제하기" />
        </form>
    </div>
</body>
</html>

SWIDEA_SITE/server/apps/ideas/templates/ideas/ideas_update.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>IDEA MODIFY</title>
    <link rel="stylesheet" href="{% static 'css/ideas_update.css' %}">
</head>
<body>
    <nav class="nav_bar">
        <div class="nav_topic">Honggu's <span style="color:greenyellow">SW IDEA </span>CLOUD</div>
        <div class="nav_tap">
            <a href="{% url 'ideas:create' %}">아이디어 등록</a>
            <a href="{% url 'ideas:list' %}">아이디어 관리</a>
            <a href="{% url 'ideas:devtool_create' %}">개발툴 등록</a>
            <a href="{% url 'ideas:devtool_list' %}">개발툴 관리</a>
        </div> 
    </nav>
    <hr />

    <div class="main_container">
        <h2 class="main_topic">Idea Modify</h2>
        <h3 class="main_info">아이디어 수정 페이지! 변경사항이 생기면 바로 바로 업데이트 합시다</h3>
        <div class="main_posts">
            <hr />
            <form action="{% url 'ideas:update' idea.pk %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p>아이디어 명 :</p>
                <input name="title" value="{{ idea.title }}" />
                <br />
                <p>이미지 등록 :</p>
                {% if idea.image %}
                    <p>
                        현재 이미지 : {{ idea.image.url }}
                        <small style="color:white">삭제하기</small>
                        <input type="checkbox" name="check" />
                    </p>
                    <input type="file" name="image" />
                {% else %}
                    <input type="file" name="image" />
                {% endif %}
                <br />
                <p>아이디어 설명 :</p>
                <textarea name="content">{{ idea.content }}</textarea>
                <br />
                <p>아이디어 관심도 :</p>
                <input name="interest" value="{{ idea.interest }}" />
                <br />
                <p>예상 개발툴 :</p>
                <select name="devtool" id="devtool">
                    <option value="" selected>{{ idea.devtool.name }}</option>
                    {% for devtool in devtools %}
                    {% if devtool.name != idea.devtool.name %}
                    <option value="{{ devtool.id }}" name="devtool">{{ devtool.name }}</option>
                    {% endif %}
                    {% endfor %}
                </select>
                <br />
                <div>
                    <input type="submit", value="저장하기" />
                </div>
            </form>
            <hr />
        </div>
    </div>
</body>
</html>